image: devkitpro/devkitarm

gba-library:
    stage: build
    script:
      - mkdir build
      - cd build
      - PLATFORM=gba BUILD_TESTS=0 cmake .. -DCMAKE_BUILD_TYPE=Debug
      - make all
    artifacts:
      name: Morpheus-GBA-$CI_JOB_NAME
      paths:
        - build/libgba_morpheus.a
      when: on_success

nds-library:
  stage: build
  script:
    - mkdir build
    - cd build
    - PLATFORM=nds BUILD_TESTS=0 cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make all
  artifacts:
    name: Morpheus-GBA-$CI_JOB_NAME
    paths:
      - build/libnds_morpheus.a
    when: on_success
