image: insightgit/morpheus

gba-library:
    stage: build
    script:
      - mkdir build
      - cd build
      - echo $DEVKITARM
      - PLATFORM=gba BUILD_TESTS=1 cmake .. -DCMAKE_BUILD_TYPE=Debug
      - cmake --build . --target morpheus
    artifacts:
      name: Morpheus-GBA-$CI_JOB_NAME
      paths:
        - build/*
      when: on_success

nds-library:
  stage: build
  script:
    - mkdir build
    - cd build
    - PLATFORM=nds BUILD_TESTS=1 cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --target morpheus
  artifacts:
    name: Morpheus-GBA-$CI_JOB_NAME
    paths:
      - build/*
    when: on_success

affine-test-gba:
  stage: test
  script:
    - cd build
    - PLATFORM=gba BUILD_TESTS=1 cmake --build . --target morpheus-gba-affine-test.gba
  dependencies:
    - gba-library
  artifacts:
    name: Morpheus-affine-test-GBA-$CI_JOB_NAME
    paths:
      - build/morpheus-gba-affine-test.gba
    when: on_success

affine-test-nds:
  stage: test
  script:
    - cd build
    - PLATFORM=nds BUILD_TESTS=1 cmake --build . --target morpheus-nds-affine-test.nds
  dependencies:
    - nds-library
  artifacts:
    name: Morpheus-affine-test-NDS-$CI_JOB_NAME
    paths:
      - build/morpheus-nds-affine-test.nds
    when: on_success

animation-test-gba:
  stage: test
  script:
    - cd build
    - PLATFORM=gba BUILD_TESTS=1 cmake --build . --target morpheus-gba-animation-test.gba
  dependencies:
    - gba-library
  artifacts:
    name: Morpheus-animation-test-GBA-$CI_JOB_NAME
    paths:
      - build/morpheus-gba-animation-test.gba
    when: on_success

animation-test-nds:
  stage: test
  script:
    - cd build
    - PLATFORM=nds BUILD_TESTS=1 cmake --build . --target morpheus-nds-animation-test.nds
  dependencies:
    - nds-library
  artifacts:
    name: Morpheus-animation-test-NDS-$CI_JOB_NAME
    paths:
      - build/morpheus-nds-animation-test.nds
    when: on_success
