image: devkitpro/devkitarm

before_script:
  - wget https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3-linux-x86_64.tar.gz
  - tar xvzf cmake-3.20.3-linux-x86_64.tar.gz
  - chmod +x cmake-3.20.3-linux-x86_64/bin/cmake

gba-library:
    stage: build
    script:
      - mkdir build
      - cd build
      - echo $DEVKITARM
      - PLATFORM=gba BUILD_TESTS=1 ../cmake-3.20.3-linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
      - make all
    artifacts:
      name: Morpheus-GBA-$CI_JOB_NAME
      paths:
        - build/libgba_morpheus.a
      when: on_success

nds-library:
  stage: build
  script:
    - mkdir build
    - cd build
    - PLATFORM=nds BUILD_TESTS=1 ../cmake-3.20.3-linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make all
  artifacts:
    name: Morpheus-GBA-$CI_JOB_NAME
    paths:
      - build/libnds_morpheus.a
    when: on_success

affine-test-gba:
  stage: test
  script:
    - cd build
    - PLATFORM=gba BUILD_TESTS=1 ../cmake-3.20.3-linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
    - ../cmake-3.20.3-linux-x86_64/bin/cmake --build ~/build --target morpheus-gba-affine-test.gba
  artifacts:
    name: Morpheus-affine-test-GBA-$CI_JOB_NAME
    paths:
      - build/morpheus-gba-affine-test.gba
    when: on_success

affine-test-nds:
  stage: test
  script:
    - cd build
    - PLATFORM=gba BUILD_TESTS=1 ../cmake-3.20.3-linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
    - ../cmake-3.20.3-linux-x86_64/bin/cmake --build ~/build --target morpheus-gba-affine-test.gba
  artifacts:
    name: Morpheus-affine-test-NDS-$CI_JOB_NAME
    paths:
      - build/morpheus-nds-affine-test.nds
    when: on_success
